export const ExamCategory = {
  THROMBOPHILIA: 'THROMBOPHILIA',
  MICROBIOLOGY: 'MICROBIOLOGY',
  ENDOCRINE_METABOLIC: 'ENDOCRINE_METABOLIC',
  IMMUNOLOGY: 'IMMUNOLOGY',
  OBSTETRIC_MARKERS: 'OBSTETRIC_MARKERS',
  IMAGING: 'IMAGING',
  BIOCHEMISTRY: 'BIOCHEMISTRY',
  HEMATOLOGY: 'HEMATOLOGY',
} as const;

export type ExamCategory = (typeof ExamCategory)[keyof typeof ExamCategory];
